language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - "gem install bundler"

before_script:
  - "bundle install --path=./vendor/bundle"

before_deploy:
  - npm run compile
  - sed -i -e "/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz HEAD > ./${TRAVIS_TAG}-compiled.tar.gz

deploy:
  - provider: releases
    api_key:
      secure: "KFhQYGDRtYk77IkXfjoX4s3+CMpex5ecG/8icwQAtY+jHSET3Hu1tEJLiE8kPUrWYqDbPPgrSlrnUCFtq6BCWpt6miuOQJAwXsIpb3cRXmqbnxAdyLBPbj5uxhuzBUxF99YliM/hS3Lr+ts3hAD+JLwzbl3tztLb3NHzSu7tMr4ElY2YtB8rZ29oNKuZd4c6jCvZ70Twi1VLj5wStgvN5MDuaF7B2nrxxPj4ry+5rUCv1+JeG+iekWSQO1GbmlC/q/X3cspNBBSmkvh9yzcpT1AMhSj6xtBYIrRMWPcMGCu3GGW50bNCM+Z9vn6aMKUK9ZrEXB/m+TCR2hfePuGvnkjekzb4RCUw9LumJf700tNTkZfTSmcQgP5VKau5/ytI+OE4aBFq2STlAMGupId1vIFdD2kJKBwkeMAubiDIWAm+Y8lwqNDw2E1eUuIg6fPMBuuI2DRF/v7pCB28SKf21ld31z97mwO1DLn8wc3T6bXmg3pqL1pNzgv+FC8gdT6DbbZWpYq2Een4Ny/DG7ZESzXFi+bGxKhKCzdSuLMGRpKcC9KPh7+XFO5BqW7Njzt2VAE7TeVZ4QoJajON3j3MDaBtfXMfmiTJM3JTpN7Si6Wopm+xe9G2S6Vg/D85Lxg4sg2I5I/RbXEdr97DdKTuB3YgA9YxsPSiPLNIMoX1gpw="
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
  - provider: npm
    email: "hiroaki@hysoftware.net"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
    api_key:
      secure: "hF8y7RcbQ61DDSqxxc4iy6rV8eMTzuIHk2s3nre8ooIaXQy5jnk5GuwRpY90eNKSOOp50efrzbugweaq/jH75APoX4SH+FPnwn0dXnOnZ06rjf4HLObo71mPn3Q0OBeX25P1wf3f8cXHC91QgFge9BEp1zErKOT7nf3JyrCEi2UvnJl3+1YCMFZXj3ZP9vZwcSwjJVvIHB8YsvbQbmme7EB6FRzExQVyZjJ6keLWQxf3pNBs9y1/D+LLQkn6j+ei3MY1aKJFQODrgy4j6bMfOAwow26jP2yMncRXx1QyMC09FKGkoJJZOkLwRdkXnfmaHE31aTzlxx0RLKWWiORxrinRy+IxgVrtr9gxwsAMg5nPcDU+RrM5lbpFqyVVQmLzef/Ol6fn2RkG8y9SpJDig52xC05Rysw14fQ6GaIkQFtN8h57bS0kQxUKaCQsBqgcl0oXg6/I3iynTKnLeSztLaK9fAtRjhwztUp/33EgchPu0RrXGkuj6Skz2z1RD5BlS1pgGJ26g5T9OxHgmpBzzKdI5rZSLHWLBOVN4mDyqSTAKDyBuD0nPlKnQNOWAiu/6M4IXNB6Zms1LIxCVuH10RkMTokBcnb+MGLd305NPkxqw6eajG/7NIUtsz71b+eh2b0nF6jeygelCYopaJwGl2NtKARik/GAiy1/uRVH8sU="
