language: node_js

node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs

before_install:
  - gem install bundler

before_script:
  - bundle install --path=./vendor/bundle

before_deploy:
  - npm run compile
  - sed -i -e "/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz HEAD > ./${TRAVIS_TAG}-compiled.tar.gz

deploy:
  - provider: releases
    api_key:
      secure: "FEe/rQPF16pAR6nwzMPPOcbZB5ezyyKQLbKr+sO7m8y0u0+IL16a4/qAMWQPG5gxqxr16QCylDplQCEXuEP8olBzx122/yRPkohEPGiZuem0LPnzep8zSPBsjAXGqNSDPBhqeXQ+z0/9XW+ChskDmt6sElYyPWm6yvQ31n4lyh6NlcrfIE3PWMOvP1g4ReoV3635Qsi77g5ijQFyshp+iyOckRiQsHcemlf41wrQGnbRznJ815UQwyYtVla44RFrKoiImRJxsEUA5SQF7zIxqyt6M+pdLRC9F8sj/oeQ2PoVBe7/z2oJs12H/0+RCHBqIw4OsVibk7rqpnCL394aJrW84hvFJBIbU5z1+h4uvusZ45dIh6UPXsWgO/i6uSzg1UP7uVkhi7j0JAm1fW+F3u8RbwbWuacPwQ8dpG/qw+eSnI6CYaWT86M1/xgwbNMyD3CY/azrlwIArtMq268dcPM9ggcCubWDYGDdIJb4RPCSoMSkXroO3RYX2SXljefv518l8oc/BKZC7CuocLrEJue/xKhbUR6E1rtFbkKg1xkJWPMuwLfI78kgvRCxz1z58UqN2q94DHAQkmd3qGByAOMWHLpaNLil2C0kA1fqRBSqHs+SPmPJPCASIZd04u6in1yRHo+Mn5ZCvtXV29PJEPxjUiY4T9N+iNkoeNPIjzY="
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      repo: Forumouth/gulp-scss
  - provider: npm
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: "fVD4NLkflhrDNioyNr8vfrgjY27DJGwJGWTA8kh9Env/4SO5s0CMI5EJDSI7GpkByn/VCmLyOHxuTB1NPvMwRD8O1Xu19bGoT/cbxZ9fC6Z1AvJBnF1i66FYNQbwgz7qwHeDvKki1gKptyXN9uUsWGi+Tt8TuKKHF1D4Wdnp5bm4qldoDNCsMvr+k4+o3E0xypC1Nl6YJnhOrJW+QTHp+Ko/D3mYywRz6Ji4V4Qd31k10+6+O1OFiCouwPUABbugA3FwLgxYfT5MTNnW+7R1SNX+4W8hyIJS2c+6zZd/o5CyBmlEbk8QAgnC2Hcgl1qApBQ+/EcKJ93/eZ1gGZFU9GTLGEOdTixDh8mOeksQpmO1CRUB3sTh8aghzjtF+7Zt287S8j/I3swMmcqOZVxNCPRA1gGHz7hGBqeG4QOPFzZhKa5rih5wGHkkR0KPLsvkRrqXvTougR/OPBkX6NBSrT5KnWVXEbXIWtrrxJv5qkus28ZaIckGFftFpIynBC78iyxZIYS4JYlljjYzPSjVl2HqgZfR+BhMbGcOOqm8Y2D8Bxgjncr1s0rwtR3oWxfpvjxbve3azciNoR6gOO+9YGbvtnsRSn8MENbhJuJx8kUONkoRz6xTgjy2sqaACB7WKRBCa6wph6wej//Zu08w6jMRzeyPYr7l00XGGRwYNKs="
    on:
      tags: true
      repo: Forumouth/gulp-scss
