language: node_js

node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs

before_install:
  - gem install bundler

before_script:
  - bundle install --path=./vendor/bundle

before_deploy:
  - npm run compile
  - sed -i -e "/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz HEAD > ./${TRAVIS_TAG}-compiled.tar.gz

deploy:
  - provider: releases
    api_key:
      secure: "LmS8oTMh7J2iY9qaPK5FaH4m3Phwu6OYIHreE82eyTquzCi2rp4mb4q+diu/SdIxZAgwpJ5dAXkTN0rEvubV+2GpnVouvtekjIGInIY2d1fxV7PpVn2/1i7L4UkLFebsPlHjUHBxaj67EdBQDPZZ41ibZIARqDx/VH0CT5Byhv8U0zsJSfakjB8hWx+f85WYA55zIL/GMekAJyaLdF9yKrjgeCkHuLpF5zR3pLC5fokwLiWYji5l4ix5i0oKrn7QZGOYtAH+IsDdZwF+7u0C0bdoZ96yLBAnMofJTM28UP88poc8klwuzViwBmWsqOzP7aasJ42LfUNSMG7nPVhUgS1eaBrccQSYNNdHFZj0iSE3KuiauFwPViyH+SwFPOl5I7CkrR9iGWeVplmqkfATQMCNAIMCpGV9Anqk9z685HEdD7s4QgcuHJ/qk0jQAvebwLh67oP/OnTq5QTyO56l/h2FP9MCwLpUbkzD5yB+cvoN9WUx6aQhBY97XVXx2lyY8nZQqOe2Ysgn/ugq3baQwz0CMTPhhAS1Hac0e3RuodKv82VJ/bMM+9hp4EJIfyYL+50/NjEudNiVkJhfyeP3oleFNEb7ILweWGp0jkl3dMNdI8Whx5fT9cyBYl3Srv+v1rH27RaIRJ8lLKxg2YPgvWPdvZRo58SSSzKmjEoI/Ls="
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      repo: Forumouth/gulp-scss
  - provider: npm
    email: hiroaki@hysoftware.net
    skip_cleanup: true
    api_key:
      secure: "fVD4NLkflhrDNioyNr8vfrgjY27DJGwJGWTA8kh9Env/4SO5s0CMI5EJDSI7GpkByn/VCmLyOHxuTB1NPvMwRD8O1Xu19bGoT/cbxZ9fC6Z1AvJBnF1i66FYNQbwgz7qwHeDvKki1gKptyXN9uUsWGi+Tt8TuKKHF1D4Wdnp5bm4qldoDNCsMvr+k4+o3E0xypC1Nl6YJnhOrJW+QTHp+Ko/D3mYywRz6Ji4V4Qd31k10+6+O1OFiCouwPUABbugA3FwLgxYfT5MTNnW+7R1SNX+4W8hyIJS2c+6zZd/o5CyBmlEbk8QAgnC2Hcgl1qApBQ+/EcKJ93/eZ1gGZFU9GTLGEOdTixDh8mOeksQpmO1CRUB3sTh8aghzjtF+7Zt287S8j/I3swMmcqOZVxNCPRA1gGHz7hGBqeG4QOPFzZhKa5rih5wGHkkR0KPLsvkRrqXvTougR/OPBkX6NBSrT5KnWVXEbXIWtrrxJv5qkus28ZaIckGFftFpIynBC78iyxZIYS4JYlljjYzPSjVl2HqgZfR+BhMbGcOOqm8Y2D8Bxgjncr1s0rwtR3oWxfpvjxbve3azciNoR6gOO+9YGbvtnsRSn8MENbhJuJx8kUONkoRz6xTgjy2sqaACB7WKRBCa6wph6wej//Zu08w6jMRzeyPYr7l00XGGRwYNKs="
    on:
      tags: true
      repo: Forumouth/gulp-scss
