language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - "gem install bundler"

before_script:
  - "bundle install --path=./vendor/bundle"

before_deploy:
  - npm run compile
  - sed -i -e "/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz HEAD > ./${TRAVIS_TAG}-compiled.tar.gz

deploy:
  - provider: releases
    api_key:
      secure: "vPHV5LoHtZztQna6wqTIhtZxa+1Yc+XqHzvUn4OsDDh+vIcYQZ5hgcfuT20EaTrOLHgOdRH9Y0aS9uCGpBhoo8DWUgUCUnrbtK/t9UTCTsNHsrLyKe+xlDF0Vhmv2goLiK05aXfNeZS421Us3Xwzll2bS9XMW/2VNIuoqSogOmZdqHHsf8OXW+f3HzAgNK5zVVFaoH8XINiGsmifxUkE0QOupbbr/tNpO8NNSfg08/jc8qWA4NvbBvoonF9c6XqJhWIbw9MqSUDwIpn2BOJ1VIp6px/ThjZub9dl5YqiW0uE8rbRL7SNBD74yh8LgAwdmvlEIvJ3RpRcdqJ1hfPdmbbWGjDZ9KGfNIXqQH640//9nitvnJStVOj5DXcOteckk/Xu5JPxG2lA93RxdB7V3Tf8msgoUBJG3o43vJtRmHW4B86kgKChCe8NL+Git9iAG27Xa27NWgxKMG+ueqXm3RaOUcCdR5i9K3nHn0fHjrDJBEhdUUOk4BL7J1cdvSwypragnJ5ESEofdE9SiaNKNcqzbr5w0X8WpFZeaI9t52Ov4N8SSfHpezLoIxNz/kN9CNrdbeYjH+17RTQzJVaIDptsYcwa4l53SRQiREgrCY2vnodeVDOUluWe4bSnaw4Zlz27+kmYvrNZDkXEBDc0gff14e476zLyw5P1rd779jw="
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
  - provider: npm
    email: "hiroaki@hysoftware.net"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
    api_key:
      secure: "hF8y7RcbQ61DDSqxxc4iy6rV8eMTzuIHk2s3nre8ooIaXQy5jnk5GuwRpY90eNKSOOp50efrzbugweaq/jH75APoX4SH+FPnwn0dXnOnZ06rjf4HLObo71mPn3Q0OBeX25P1wf3f8cXHC91QgFge9BEp1zErKOT7nf3JyrCEi2UvnJl3+1YCMFZXj3ZP9vZwcSwjJVvIHB8YsvbQbmme7EB6FRzExQVyZjJ6keLWQxf3pNBs9y1/D+LLQkn6j+ei3MY1aKJFQODrgy4j6bMfOAwow26jP2yMncRXx1QyMC09FKGkoJJZOkLwRdkXnfmaHE31aTzlxx0RLKWWiORxrinRy+IxgVrtr9gxwsAMg5nPcDU+RrM5lbpFqyVVQmLzef/Ol6fn2RkG8y9SpJDig52xC05Rysw14fQ6GaIkQFtN8h57bS0kQxUKaCQsBqgcl0oXg6/I3iynTKnLeSztLaK9fAtRjhwztUp/33EgchPu0RrXGkuj6Skz2z1RD5BlS1pgGJ26g5T9OxHgmpBzzKdI5rZSLHWLBOVN4mDyqSTAKDyBuD0nPlKnQNOWAiu/6M4IXNB6Zms1LIxCVuH10RkMTokBcnb+MGLd305NPkxqw6eajG/7NIUtsz71b+eh2b0nF6jeygelCYopaJwGl2NtKARik/GAiy1/uRVH8sU="
