language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - "gem install bundler"

before_script:
  - "bundle install --path=./vendor/bundle"

before_deploy:
  - npm run compile
  - sed -i -e "/lib\//D" .gitignore
  - git config --global user.email "test@example.com"
  - git config --global user.name "Mr. Travis CI"
  - git add .
  - git commit -m "Commit to make tarball"
  - git archive --format=tar.gz HEAD > ./${TRAVIS_TAG}-compiled.tar.gz

deploy:
  - provider: releases
    api_key:
      secure: "I6cdIpwoHMabeUtwZ701lo4f3YEsC306/yBweABUDwj7gkJcGXUC1v5uTYrddU1o4mg/lp/TGShbkI6c4ywOyMtiVbnibXRoemLvT+TnEksX/paSadx2Yu7wWOpLssWwggrAPkJxQqNG9BQW1s4a2b5D5tBDFaK2OssQ9aS9k1GSyGW4OZJGzw0Au4iqVqSbxSAE146p6ex8+K/FEJ7aoarK7/e57cyUD3gr6e93lgCv56kSVwZmtAcZanT2AGjancXqDMUW20cPzKbI2TmV537n+7OBBZQ9ZocAKN9df/sWygYwiDRPLPBiclM9Vf+3gKYkOp8pdH+HaISif5e+B4cFJ1I4/1F/Crre/573g3rJv3BVM6NuF4yXfDZBjWBW7muhXt/iCPWX2qp/LH5hB7UOZgL0GN65s6MqH/Jn+OuD3IpLQ7ByNaKQz2SNUNftmUzDwE9FSUL9dfuFVRoDdPgKbIHipp//eFfuSXe4rx+mMU2TTfyasi7VoyQlVZ1dne5NNFzcx0pof5dHKjyomjlJQ1C3S1l/BiJWpEUFDB1i2ooztliGu9uD0ejQIKfuYZ8tI2MNsSFii76X3u2QI0X+VIaHtj5q4xG0T6igZ3z54xUuQAB5weWcrmFUkOyD2LGl2eOIxXKDGaofzdiujo0edNPDhRRXQZUPx0OB9v4="
    file: "${TRAVIS_TAG}-compiled.tar.gz"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
  - provider: npm
    email: "hiroaki@hysoftware.net"
    skip_cleanup: true
    on:
      repo: Forumouth/gulp-scss
      tags: true
    api_key:
      secure: "hF8y7RcbQ61DDSqxxc4iy6rV8eMTzuIHk2s3nre8ooIaXQy5jnk5GuwRpY90eNKSOOp50efrzbugweaq/jH75APoX4SH+FPnwn0dXnOnZ06rjf4HLObo71mPn3Q0OBeX25P1wf3f8cXHC91QgFge9BEp1zErKOT7nf3JyrCEi2UvnJl3+1YCMFZXj3ZP9vZwcSwjJVvIHB8YsvbQbmme7EB6FRzExQVyZjJ6keLWQxf3pNBs9y1/D+LLQkn6j+ei3MY1aKJFQODrgy4j6bMfOAwow26jP2yMncRXx1QyMC09FKGkoJJZOkLwRdkXnfmaHE31aTzlxx0RLKWWiORxrinRy+IxgVrtr9gxwsAMg5nPcDU+RrM5lbpFqyVVQmLzef/Ol6fn2RkG8y9SpJDig52xC05Rysw14fQ6GaIkQFtN8h57bS0kQxUKaCQsBqgcl0oXg6/I3iynTKnLeSztLaK9fAtRjhwztUp/33EgchPu0RrXGkuj6Skz2z1RD5BlS1pgGJ26g5T9OxHgmpBzzKdI5rZSLHWLBOVN4mDyqSTAKDyBuD0nPlKnQNOWAiu/6M4IXNB6Zms1LIxCVuH10RkMTokBcnb+MGLd305NPkxqw6eajG/7NIUtsz71b+eh2b0nF6jeygelCYopaJwGl2NtKARik/GAiy1/uRVH8sU="
