environment:
  nodejs_version: "0.12"

clone_folder: c:\projects\gulp-scss

install:
  - gem install bundler
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - bundle install --path=./vendor/bundle

test_script:
  - node --version
  - npm --version
  - npm test

build: off

artifacts:
  - path: tests\results
    name: Test result
    type: zip

on_failure:
  - ps: Push-AppveyorArtifact .\
