environment:
  nodejs_version: "0.12"

install:
  - gem install bundler
  - ps: Install-Product node 3
  - npm install
  - bundle install --path=./vendor/bundle

test_script:
  - node --version
  - npm --version
  - npm test
